version: '3.1'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8001:8000"

  memcached:
    image: memcached
    ports:
      - '11211:11211'
    entrypoint:
      - memcached
      - -m 64
