# Generated by Django 4.2.7 on 2023-11-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_spending', '0006_productcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcount',
            name='count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
