# Generated by Django 4.2.7 on 2023-11-10 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money_spending', '0008_rename_count_productcount_number_of_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='money_spending.productcount'),
        ),
    ]
