# Generated by Django 4.2.7 on 2023-11-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_spending', '0009_expense_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='product_id',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
