# Generated by Django 4.2.7 on 2023-11-11 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money_spending', '0010_alter_expense_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='product_id',
            new_name='product',
        ),
    ]
